### ISSUE TITLE
Help with Kanye wlan module

### ISSUE THREAD

**Issue by JjersaR** [Z-8Bit/Polybar-Collection#1]
I am using the configuration or Kanye style, and when using bluetooth or flameshot, I get the icons above the network name, do you know how to fix this?

![image](https://github.com/Z-8Bit/Polybar-Collection/assets/86206596/383d9a3c-751f-426d-a2bb-a13e8dfd21e4)

**Comment by Z-8Bit** [comment]
Hi, firstly I'd like to thank you for using my configuration - it means a lot to me. Secondly, I am aware that there is an issue with the tray. I think polybar has changed config for the tray in the recent updates but I haven't come around to checking it out due to personal life taking all my time. I will definitely check it out sooner than later but can't give you an estimate. Thanks for reporting it.

**Comment by Z-8Bit** [comment]
Hi, I've fixed this issue now. You can download the repo (or clone it) and try now. Thanks!
